/**
 * The five hero accounts, authored at full depth, plus their legal entities
 * and fund ranges.
 *
 * Illustrative prototype data. Organisation names, entity names and fund-range
 * structures are public corporate facts. Everything commercial attached to them
 * — Broadridge relationships, renewal windows, opportunity values, hypotheses —
 * is illustrative and is labelled as such throughout the interface.
 */
import type { Account, Fund, LegalEntity } from "../types";

export const HERO_ACCOUNTS: Account[] = [
  {
    id: "acc-schroders",
    name: "Schroders",
    legalName: "Schroders plc",
    type: "asset-manager",
    tier: "strategic",
    hqMarketId: "gb",
    relationship: "existing-client",
    ownerId: "bp-james-howard",
    story:
      "Existing communications client with rising cross-border complexity and no confirmed central distribution model.",
    whatChanged:
      "New UCITS host-market activity across Germany, Italy and Spain, alongside two senior European appointments.",
    whereWeStand:
      "Existing Luxembourg Fund Communication Solutions relationship, renewing in 120 days. No confirmed cross-border distribution service relationship.",
    whatToDoNext:
      "Ask the existing Luxembourg client director to validate how registration, local representation and document distribution are handled today, before the renewal conversation opens.",
    stillToLearn: [
      "Who owns the European distribution operating model.",
      "How registrations and local representation are handled today.",
      "Which provider model is in place.",
      "Whether the new host markets are live or planned.",
      "Who holds budget and procurement ownership.",
    ],
    coverage: "covered",
    health: "stable",
    marker: "new",
    strategicValue: 5,
    aum: "£770bn",
    hero: true,
  },
  {
    id: "acc-nordea",
    name: "Nordea Asset Management",
    legalName: "Nordea Investment Management AB",
    type: "bank-asset-manager",
    tier: "strategic",
    hqMarketId: "dk",
    relationship: "existing-client",
    ownerId: "bp-tom-eriksen",
    story:
      "Live cross-border and regulatory opportunity with a genuinely engaged operations sponsor and no confirmed decision route.",
    whatChanged:
      "The mutual next step agreed in the July working session passed without being rescheduled.",
    whereWeStand:
      "The customer problem and the operational sponsor are confirmed. The economic buyer, procurement route and current provider model are not.",
    whatToDoNext:
      "Agree a decision-process review with the operations sponsor. Confirm the executive owner, success criteria, current provider, procurement path and a target decision date.",
    stillToLearn: [
      "Who signs off spend of this size in the fund operations line.",
      "Which procurement route applies to a group-bank subsidiary.",
      "Which provider handles regulatory reporting today.",
      "Whether the 2027 PRIIPs cycle is the real forcing date.",
    ],
    coverage: "covered",
    health: "attention",
    marker: "attention",
    strategicValue: 5,
    aum: "€270bn",
    hero: true,
  },
  {
    id: "acc-waystone",
    name: "Waystone",
    legalName: "Waystone Group",
    type: "third-party-manco",
    tier: "strategic",
    hqMarketId: "ie",
    relationship: "prospect",
    ownerId: "bp-ravi-nair",
    story:
      "Third-party ManCo absorbing acquired management-company business, with a growing underlying manager base and no Broadridge relationship.",
    whatChanged:
      "The Luxembourg management company took on further permissions and completed the integration of an acquired ManCo business, under a new chief executive.",
    whereWeStand:
      "No existing Broadridge commercial relationship. Product fit for fund communications and regulatory reporting is high; nothing has been validated with the client.",
    whatToDoNext:
      "Build the buying-system map before any outreach. Establish whether the Luxembourg ManCo buys independently of group.",
    stillToLearn: [
      "Whether communications and reporting are bought at ManCo or group level.",
      "How the acquired ManCo book is being operationally consolidated.",
      "Which providers came across with the acquired business.",
      "Whether underlying managers or the ManCo select the document provider.",
      "Who holds the budget for the consolidated operating model.",
    ],
    coverage: "thin",
    health: "stable",
    marker: "new",
    strategicValue: 4,
    aum: "$2.5tn serviced",
    hero: true,
  },
  {
    id: "acc-janushenderson",
    name: "Janus Henderson Investors",
    legalName: "Janus Henderson Group plc",
    type: "asset-manager",
    tier: "strategic",
    hqMarketId: "gb",
    relationship: "existing-client",
    ownerId: "bp-claire-dubois",
    story:
      "Stable communications relationship that has gone quiet, with a renewal inside 90 days and no agreed scope.",
    whatChanged:
      "Host-market coverage widened across the Irish range while engagement on our side dropped to nothing for eleven weeks.",
    whereWeStand:
      "Fund Communication Solutions is live and healthy operationally. The renewal has no agreed scope, no stakeholder plan and no scheduled conversation.",
    whatToDoNext:
      "Open the renewal conversation now on service quality, not on expansion. Re-establish the stakeholder plan before raising the widened host-market footprint.",
    stillToLearn: [
      "Who now owns the renewal decision on the client side.",
      "Whether the quiet period reflects satisfaction or disengagement.",
      "Whether the widened host-market coverage changed their document workload.",
      "Whether any competitor has been invited in.",
    ],
    coverage: "thin",
    health: "attention",
    marker: "attention",
    strategicValue: 4,
    aum: "$400bn",
    hero: true,
  },
  {
    id: "acc-allfunds",
    name: "Allfunds",
    legalName: "Allfunds Group plc",
    type: "platform-distributor",
    tier: "strategic",
    hqMarketId: "es",
    relationship: "prospect",
    ownerId: "bp-elena-costa",
    story:
      "Distribution platform with strong intelligence and data potential, several warm internal routes and no active deal.",
    whatChanged:
      "A senior product and distribution appointment in the US, and a measurable shift in platform flows across Iberia and Italy.",
    whereWeStand:
      "No active opportunity. Multiple warm internal relationship routes exist and none have been used.",
    whatToDoNext:
      "Build the account plan. Establish which product decisions sit with the new US appointment and which stay with European product.",
    stillToLearn: [
      "Whether distribution-data and preference intelligence are bought centrally.",
      "Which internal route is genuinely warm rather than merely known.",
      "How the divested management-company business changed their service needs.",
      "What the flow shift in Iberia and Italy reflects commercially.",
    ],
    coverage: "thin",
    health: "stable",
    marker: "new",
    strategicValue: 4,
    aum: "€1.5tn AuA",
    hero: true,
  },
];

export const HERO_ENTITIES: LegalEntity[] = [
  {
    id: "ent-schroders-lux",
    name: "Schroder Investment Management (Europe) S.A.",
    accountId: "acc-schroders",
    role: "ucits-manco",
    domicileMarketId: "lu",
    regulator: "CSSF",
  },
  {
    id: "ent-schroders-uk",
    name: "Schroder Investment Management Limited",
    accountId: "acc-schroders",
    role: "distribution-entity",
    domicileMarketId: "gb",
    regulator: "FCA",
  },
  {
    id: "ent-nordea-lux",
    name: "Nordea Investment Funds S.A.",
    accountId: "acc-nordea",
    role: "ucits-manco",
    domicileMarketId: "lu",
    regulator: "CSSF",
  },
  {
    id: "ent-nordea-dk",
    name: "Nordea Investment Management AB, Danish branch",
    accountId: "acc-nordea",
    role: "distribution-entity",
    domicileMarketId: "dk",
    regulator: "Finanstilsynet",
  },
  {
    id: "ent-waystone-lux",
    name: "Waystone Management Company (Lux) S.A.",
    accountId: "acc-waystone",
    role: "third-party-manco",
    domicileMarketId: "lu",
    regulator: "CSSF",
  },
  {
    id: "ent-waystone-ie",
    name: "Waystone Management Company (IE) Limited",
    accountId: "acc-waystone",
    role: "third-party-manco",
    domicileMarketId: "ie",
    regulator: "Central Bank of Ireland",
  },
  {
    id: "ent-jh-lux",
    name: "Henderson Management S.A.",
    accountId: "acc-janushenderson",
    role: "ucits-manco",
    domicileMarketId: "lu",
    regulator: "CSSF",
  },
  {
    id: "ent-jh-ie",
    name: "Janus Henderson Investors Europe Limited",
    accountId: "acc-janushenderson",
    role: "distribution-entity",
    domicileMarketId: "ie",
    regulator: "Central Bank of Ireland",
  },
  {
    id: "ent-allfunds-es",
    name: "Allfunds Bank S.A.U.",
    accountId: "acc-allfunds",
    role: "platform-operator",
    domicileMarketId: "es",
    regulator: "CNMV",
  },
  {
    id: "ent-allfunds-lux",
    name: "Allfunds International S.A.",
    accountId: "acc-allfunds",
    role: "distribution-entity",
    domicileMarketId: "lu",
    regulator: "CSSF",
  },
];

export const HERO_FUNDS: Fund[] = [
  {
    id: "fund-sisf-globaleq",
    name: "Schroder ISF Global Equity",
    accountId: "acc-schroders",
    entityId: "ent-schroders-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "Global equity",
    hostMarketIds: ["gb", "ch", "nl", "at", "de", "it", "es"],
    newHostMarketIds: ["de", "it", "es"],
    shareClasses: 42,
  },
  {
    id: "fund-sisf-eurocorp",
    name: "Schroder ISF EURO Corporate Bond",
    accountId: "acc-schroders",
    entityId: "ent-schroders-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "Euro credit",
    hostMarketIds: ["gb", "ch", "nl", "be", "de", "it"],
    newHostMarketIds: ["de", "it"],
    shareClasses: 31,
  },
  {
    id: "fund-sisf-sustainable",
    name: "Schroder ISF Sustainable European Equity",
    accountId: "acc-schroders",
    entityId: "ent-schroders-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "European equity",
    hostMarketIds: ["gb", "nl", "se", "es"],
    newHostMarketIds: ["es"],
    shareClasses: 24,
  },
  {
    id: "fund-nordea1-stableeq",
    name: "Nordea 1 — Global Stable Equity Fund",
    accountId: "acc-nordea",
    entityId: "ent-nordea-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "Global equity",
    hostMarketIds: ["dk", "se", "no", "fi", "de", "it", "es", "fr", "ch"],
    shareClasses: 38,
  },
  {
    id: "fund-nordea1-covbond",
    name: "Nordea 1 — European Covered Bond Fund",
    accountId: "acc-nordea",
    entityId: "ent-nordea-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "European credit",
    hostMarketIds: ["dk", "se", "no", "fi", "de", "at", "ch", "nl"],
    shareClasses: 29,
  },
  {
    id: "fund-waystone-platform",
    name: "Waystone Lux ManCo umbrella — hosted sub-funds",
    accountId: "acc-waystone",
    entityId: "ent-waystone-lux",
    domicileMarketId: "lu",
    structure: "UCITS",
    assetClass: "Multiple, third-party managed",
    hostMarketIds: ["de", "it", "es", "fr", "nl", "ch", "gb", "se"],
    newHostMarketIds: ["fr", "nl"],
    shareClasses: 186,
  },
  {
    id: "fund-waystone-ie-umbrella",
    name: "Waystone Ireland ICAV platform — hosted sub-funds",
    accountId: "acc-waystone",
    entityId: "ent-waystone-ie",
    domicileMarketId: "ie",
    structure: "ICAV",
    assetClass: "Multiple, third-party managed",
    hostMarketIds: ["gb", "de", "it", "ch"],
    shareClasses: 94,
  },
  {
    id: "fund-jh-horizon-euro",
    name: "Janus Henderson Horizon Euro Corporate Bond Fund",
    accountId: "acc-janushenderson",
    entityId: "ent-jh-lux",
    domicileMarketId: "lu",
    structure: "SICAV",
    assetClass: "Euro credit",
    hostMarketIds: ["gb", "de", "it", "es", "ch", "nl", "at"],
    newHostMarketIds: ["at"],
    shareClasses: 26,
  },
  {
    id: "fund-jh-capital-global",
    name: "Janus Henderson Capital Funds — Global Research",
    accountId: "acc-janushenderson",
    entityId: "ent-jh-ie",
    domicileMarketId: "ie",
    structure: "ICAV",
    assetClass: "Global equity",
    hostMarketIds: ["gb", "de", "it", "es", "ch", "sg", "hk"],
    newHostMarketIds: ["sg", "hk"],
    shareClasses: 33,
  },
  {
    id: "fund-allfunds-distributed",
    name: "Allfunds distributed fund universe",
    accountId: "acc-allfunds",
    entityId: "ent-allfunds-es",
    domicileMarketId: "es",
    structure: "UCITS",
    assetClass: "Third-party distributed",
    hostMarketIds: ["es", "it", "pt", "ch", "gb", "lu", "ae", "sg", "cl"],
    shareClasses: 0,
  },
];
