/**
 * Tasks.
 *
 * Every task is bound to a real object — an account, deal, person, hypothesis
 * or event — and carries the reason it exists. There are no standalone to-dos,
 * because a task nobody can trace back to a commercial reason is the first
 * thing a seller stops doing.
 *
 * Illustrative prototype data.
 */
import type { Task } from "../types";

const t = (
  id: string,
  title: string,
  linkedToKind: Task["linkedToKind"],
  linkedToId: string,
  accountId: string,
  whyThisMatters: string,
  ownerId: string,
  due: string,
  dueLabel: string,
  status: Task["status"],
  extra: Partial<Task> = {},
): Task => ({
  id,
  title,
  linkedToKind,
  linkedToId,
  accountId,
  whyThisMatters,
  ownerId,
  due,
  dueLabel,
  status,
  createdBy: "System suggestion",
  ...extra,
});

export const TASKS: Task[] = [
  t(
    "tsk-schroders-provider",
    "Confirm the current registration and local-representation model",
    "hypothesis",
    "hyp-schroders-xborder",
    "acc-schroders",
    "The group has expanded into three host markets, but how registration and local representation are handled today is unknown. Everything downstream depends on this answer.",
    "bp-james-howard",
    "2026-09-11",
    "Friday",
    "mine",
    { suggestedRoute: "Ask Sarah Patel, the existing Luxembourg client director." },
  ),
  t(
    "tsk-schroders-renewal-prep",
    "Prepare the joint renewal and operating model review",
    "opportunity",
    "opp-schroders-renewal",
    "acc-schroders",
    "The renewal conversation is dated for 24 September and is the only agreed forum where the widened host-market footprint can be raised without it reading as a renewal tactic.",
    "bp-sarah-patel",
    "2026-09-22",
    "22 September",
    "mine",
  ),
  t(
    "tsk-schroders-schwyzer-remit",
    "Establish whether the European client group role owns the operating model",
    "person",
    "px-schroders-schwyzer",
    "acc-schroders",
    "We have recorded a likely executive sponsor at medium confidence. Approaching before confirming the remit risks burning the only route we have.",
    "bp-james-howard",
    "2026-09-18",
    "18 September",
    "waiting",
    { blockedBy: "Awaiting response from the Luxembourg client-services owner." },
  ),
  t(
    "tsk-nordea-reset",
    "Agree a decision-process review with the operations sponsor",
    "opportunity",
    "opp-nordea-xborder",
    "acc-nordea",
    "The mutual next step expired on 21 August and has not been rescheduled. Until a decision route exists, £640k cannot be forecast.",
    "bp-tom-eriksen",
    "2026-09-09",
    "Wednesday",
    "mine",
    { approvalNeeded: false },
  ),
  t(
    "tsk-nordea-buyer",
    "Identify the economic buyer for fund operations spend",
    "opportunity",
    "opp-nordea-xborder",
    "acc-nordea",
    "No economic buyer is recorded on a late-stage deal. This is the single condition holding the forecast.",
    "bp-tom-eriksen",
    "2026-09-16",
    "16 September",
    "mine",
    { suggestedRoute: "Ask the operations sponsor directly at the decision-process review." },
  ),
  t(
    "tsk-nordea-provider",
    "Establish which provider handles regulatory reporting today",
    "opportunity",
    "opp-nordea-xborder",
    "acc-nordea",
    "Scope and value cannot be set without knowing what is already covered, and a displacement conversation should never start before this is known.",
    "bp-anna-weber",
    "2026-09-19",
    "19 September",
    "team",
  ),
  t(
    "tsk-waystone-buyermap",
    "Build the buying-system map for the Luxembourg management company",
    "hypothesis",
    "hyp-waystone-manco",
    "acc-waystone",
    "Product fit is high and the consolidation timing is favourable, but we do not know whether the ManCo or group buys. One wrong approach closes the account for a year.",
    "bp-ravi-nair",
    "2026-09-19",
    "19 September",
    "mine",
  ),
  t(
    "tsk-waystone-providers",
    "Establish which providers transferred with the acquired ManCo book",
    "event",
    "ev-waystone-consolidation",
    "acc-waystone",
    "The consolidation is the moment a provider decision is genuinely open. Knowing the incumbents determines whether there is anything to compete for.",
    "bp-ravi-nair",
    "2026-09-25",
    "25 September",
    "team",
  ),
  t(
    "tsk-jh-renewal-open",
    "Open the renewal conversation on service quality",
    "opportunity",
    "opp-jh-renewal",
    "acc-janushenderson",
    "76 days to renewal, eleven weeks of silence and no agreed scope. Every week without contact makes the conversation harder.",
    "bp-claire-dubois",
    "2026-09-09",
    "Wednesday",
    "mine",
    { approvalNeeded: false },
  ),
  t(
    "tsk-jh-owner",
    "Confirm who owns the renewal decision this cycle",
    "account",
    "acc-janushenderson",
    "acc-janushenderson",
    "The previous decision owner has not been confirmed as still in role. Renewing into the wrong stakeholder is how quiet accounts become lost ones.",
    "bp-claire-dubois",
    "2026-09-12",
    "Friday",
    "mine",
  ),
  t(
    "tsk-jh-competitor",
    "Establish whether an alternative provider has been approached",
    "opportunity",
    "opp-jh-renewal",
    "acc-janushenderson",
    "Eleven weeks of silence ahead of a renewal has more than one explanation, and the expensive one needs ruling out first.",
    "bp-peter-quinn",
    "2026-09-15",
    "15 September",
    "waiting",
    { blockedBy: "Awaiting delivery team's next service touchpoint." },
  ),
  t(
    "tsk-allfunds-plan",
    "Build the account plan and map the internal routes",
    "hypothesis",
    "hyp-allfunds-intel",
    "acc-allfunds",
    "Several warm internal routes exist and none have been used. Spending one without a plan wastes the only asset the account has.",
    "bp-elena-costa",
    "2026-09-19",
    "19 September",
    "mine",
  ),
  t(
    "tsk-allfunds-central",
    "Establish whether distribution data is bought centrally or regionally",
    "person",
    "px-allfunds-alonso",
    "acc-allfunds",
    "A product-development background suggests appetite, but not authority. The buying level determines whether the US appointment is relevant to us at all.",
    "bp-elena-costa",
    "2026-09-26",
    "26 September",
    "team",
  ),
  t(
    "tsk-amundi-procurement",
    "Confirm the procurement route ahead of the scope session",
    "opportunity",
    "opp-amundi-consolidation",
    "acc-amundi",
    "£2.4m with no established procurement route. The scope session will produce a plan nobody can buy.",
    "bp-marta-oliveira",
    "2026-09-24",
    "24 September",
    "mine",
  ),
  t(
    "tsk-gsam-buyermap",
    "Build the buying-system map above the architecture contact",
    "opportunity",
    "opp-gsam-imops",
    "acc-gsam",
    "The largest deal in the pipeline is sponsored by an architect with no confirmed economic buyer and no legal engagement.",
    "bp-lucy-chen",
    "2026-09-23",
    "23 September",
    "mine",
  ),
  t(
    "tsk-abrdn-escalate",
    "Escalate the renewal and seek a dated commitment",
    "opportunity",
    "opp-abrdn-renewal",
    "acc-abrdn",
    "The close date has moved twice and two scheduling attempts were deferred. Without a dated commitment this week, treat it as lost and plan accordingly.",
    "bp-claire-dubois",
    "2026-09-10",
    "Thursday",
    "mine",
    { approvalNeeded: true },
  ),
  t(
    "tsk-invesco-provider",
    "Validate the incumbent provider arrangement",
    "opportunity",
    "opp-invesco-regworkflow",
    "acc-invesco",
    "A displacement conversation without knowing the incumbent is a campaign, not a sales approach.",
    "bp-anna-weber",
    "2026-09-17",
    "17 September",
    "team",
  ),
  t(
    "tsk-dws-legal",
    "Confirm the legal review date and signature path",
    "opportunity",
    "opp-dws-regworkflow",
    "acc-dws",
    "Every other condition on this deal is met. Legal review is the only thing between here and close.",
    "bp-david-lange",
    "2026-09-15",
    "15 September",
    "mine",
  ),
  t(
    "tsk-market-brief-de",
    "Prepare the German cross-border account brief",
    "market",
    "de",
    "acc-schroders",
    "Germany carries the highest concentration of new client-linked fund activity this month. One brief serves several account conversations.",
    "bp-nadia-haddad",
    "2026-09-18",
    "18 September",
    "team",
  ),
  t(
    "tsk-schroders-brief-done",
    "Circulate the cross-border activity summary to the account team",
    "event",
    "ev-schroders-xborder",
    "acc-schroders",
    "The account team needed the verified market activity before the renewal review could be planned.",
    "bp-nadia-haddad",
    "2026-09-02",
    "2 September",
    "completed",
    { completedBy: "Nadia Haddad", approvedBy: "James Howard" },
  ),
  t(
    "tsk-nordea-notes",
    "Capture the July operating model session outcome",
    "opportunity",
    "opp-nordea-xborder",
    "acc-nordea",
    "The session confirmed the operational problem and the sponsor. Recording it is what makes the deal's health statement defensible.",
    "bp-tom-eriksen",
    "2026-07-25",
    "25 July",
    "completed",
    { completedBy: "Tom Eriksen" },
  ),
];
